# Jaimason C. Trenholm

- **Email**: Jaimason.Trenholm@gmail.com
- **LinkedIn**: Jaimason Trenholm
- **Phone**: (737) 275-1732

## Education

**Bachelor of Science in Business Management**  
Brigham Young University-Idaho, Rexburg, ID  
- Culinary Arts
- Data Science and Analytics
- Business Finance
- Minor in Small Business Operations

## Experience

### Line Cook
Aug. 2022 – Sep 2023  
Life Care Services LLC, Georgetown, TX  
- Prepared food items consistently and in compliance with recipes, portioning, cooking, and waste control guidelines.
- Operated various kitchen appliances such as a blender, oven, grill, or stand mixer.
- Ensured freshness of food and ingredients by checking for quality, keeping track of old and new items, and rotating stock.
- Assisted in prep work, such as washing vegetables or butchering meat when needed.
- Adhered to sanitation policies at all times when handling food products.

### Teachers Assistant
Aug. 2022 – Jun 2023  
Georgetown ISD, Georgetown, TX  
- Facilitated small group instruction and activities for students of varying abilities.
- Supported teachers by preparing materials, setting up equipment, and organizing supplies.
- Helped teacher plan lessons utilizing various teaching strategies including hands-on activities and technology integration.

### Team Member
May 2020 – Aug. 2022  
Whataburger, Georgetown, TX  
- Ensured cash values were consistent with sales and no money was lost.
- Managed team on the floor, ensuring efficiency and timeliness.
- Used customer service skills to provide customers with the best experience possible.

## Leadership/Skills

- Competed in the state of Texas winning 1st place in the culinary division.
- Helped rewrite the handbook for the Delaney, resulting in better training for new employees.
- 4 years of knife skills experience.
- Helped manage funds and make food orders at the Delaney.



<!-- ### Footer

Last updated: May 2013 -->